# Author: Tom Sapletta · Part of the ifURI solution — GENERATED by urirun-reasoner.
"""urirun-connector-document — Headless document creation (Markdown/TXT/ODT) — no GUI editor, no LibreOffice.

Generated autonomously to satisfy a capability the reasoner found blocked (no connector
served the document:// scheme). Built to URI_NATIVE_CONNECTOR_CHECKLIST: lazy imports,
handlers never raise (urirun envelope), queries in-process.
"""
from __future__ import annotations

from typing import Any

import urirun

CONNECTOR_ID = "document"
conn = urirun.connector(CONNECTOR_ID, scheme="document")


def _ok(**kw: Any) -> dict[str, Any]:
    return urirun.ok(connector=CONNECTOR_ID, **kw)


def _fail(msg: str, action: str, **extra: Any) -> dict[str, Any]:
    return urirun.fail(msg, connector=CONNECTOR_ID, action=action, **extra)


@conn.handler("document/command/create", isolated=True,
              meta={"label": "Create a document artifact (md/txt/odt) with title + body — headless"})
def document_command_create(path: str = '', title: str = '', body: str = '', format: str = 'md') -> dict[str, Any]:
    """Write a document to `path`. format md|txt writes text; odt uses odfpy. Returns the artifact path + bytes."""
    try:
        from pathlib import Path
        p = Path(path).expanduser()
        p.parent.mkdir(parents=True, exist_ok=True)
        if format in ('md', 'txt'):
            text = (('# ' + title + '\n\n') if title and format=='md' else ((title+'\n\n') if title else '')) + body
            p.write_text(text, encoding='utf-8')
        elif format == 'odt':
            from odf.opendocument import OpenDocumentText
            from odf.text import H, P
            d = OpenDocumentText()
            if title: d.text.addElement(H(outlinelevel=1, text=title))
            for para in body.split('\n\n'):
                d.text.addElement(P(text=para))
            d.save(str(p))
        else:
            return _fail('unsupported format (md|txt|odt)', 'document-create')
        return _ok(action='document-create', path=str(p), bytes=p.stat().st_size, format=format)
    except Exception as exc:  # noqa: BLE001
        return _fail(str(exc), "document-create")


@conn.handler("document/query/read", isolated=False,
              meta={"label": "Read a document artifact back (verify postcondition)"})
def document_query_read(path: str = '') -> dict[str, Any]:
    """Read a text/markdown document back for postcondition verification."""
    try:
        from pathlib import Path
        p = Path(path).expanduser()
        if not p.exists(): return _fail('not found: ' + str(p), 'document-read')
        return _ok(action='document-read', path=str(p), bytes=p.stat().st_size, exists=True)
    except Exception as exc:  # noqa: BLE001
        return _fail(str(exc), "document-read")


def urirun_bindings() -> dict[str, Any]:
    return conn.bindings()


def connector_manifest() -> dict[str, Any]:
    return urirun.load_manifest(__package__) or {"id": CONNECTOR_ID}


def main(argv: list[str] | None = None) -> int:
    return conn.cli(argv, manifest_prose=urirun.load_manifest(__package__))


if __name__ == "__main__":
    raise SystemExit(main())
